# Create environment via
# conda env create -f environment.yml
name: piecewise-vanilla-model
channels:
  - defaults
  - conda-forge
dependencies:
  - ipykernel
  - jupyter
  - python
  - numpy
  - pandas
  - plotly
  - scipy
